# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM node:lts AS build

WORKDIR /code
COPY package.json /code/package.json
COPY package-lock.json /code/package-lock.json

RUN npm ci
COPY . /code
RUN ["npm", "run", "build"]

FROM nginx:1.25-alpine

COPY --from=build /code/build /usr/share/nginx/html
COPY nginx.ecs.conf /etc/nginx/conf.d/default.conf
