version: "3"

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - spring-mysql

  backend:
    image: klisman013/java-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/example
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - react-spring
      - spring-mysql

  frontend:
    image: klisman013/react-frontend:latest
    depends_on:
      - backend
    networks:
      - react-spring

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./eb-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - react-spring

networks:
  react-spring:
  spring-mysql:
